# -*- coding: utf-8 -*-
"""PRACTICAL - 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o22fN3AXhl0NA7g53fP8fRCCGmPj2Sgp

IMPLEMENTATION of graph and searching (DFS and BFS)
"""

import time
from collections import deque


# --------------------------------
# DFS - Depth First Search
# --------------------------------

def dfs(graph, start, visited):
    visited.add(start)
    print(start, end=" ")

    for neighbor in graph[start]:
        if neighbor not in visited:
            dfs(graph, neighbor, visited)


# --------------------------------
# BFS - Breadth First Search
# --------------------------------

def bfs(graph, start):
    visited = set()
    queue = deque()

    visited.add(start)
    queue.append(start)

    while queue:
        vertex = queue.popleft()
        print(vertex, end=" ")

        for neighbor in graph[vertex]:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)


# --------------------------------
# User Input
# --------------------------------

vertices = int(input("Enter number of vertices: "))
edges = int(input("Enter number of edges: "))

graph = {}

# Create empty adjacency list
for i in range(vertices):
    graph[i] = []

print("\nEnter edges (u v):")

for i in range(edges):
    u, v = map(int, input(f"Edge {i + 1}: ").split())

    # Undirected graph
    graph[u].append(v)
    graph[v].append(u)


start_vertex = int(input("\nEnter starting vertex: "))


# --------------------------------
# DFS Execution
# --------------------------------

visited = set()

start_time = time.perf_counter()

print("\nDFS Traversal:", end=" ")
dfs(graph, start_vertex, visited)

end_time = time.perf_counter()

dfs_time = end_time - start_time


# --------------------------------
# BFS Execution
# --------------------------------

start_time = time.perf_counter()

print("\nBFS Traversal:", end=" ")
bfs(graph, start_vertex)

end_time = time.perf_counter()

bfs_time = end_time - start_time


# --------------------------------
# Execution Times
# --------------------------------

print("\n\nDFS Execution Time:", dfs_time, "seconds")
print("BFS Execution Time:", bfs_time, "seconds")

"""READ ME

DFS and BFS are efficient graph traversal algorithms used to visit all reachable vertices of a graph.\
 Both DFS and BFS have a **time complexity of O(V + E)** and a **space complexity of O(V)**.\
 The execution time is measured using `time.perf_counter()` and may vary depending on the system.
"""