# -*- coding: utf-8 -*-
"""READ ME - 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DbX_Y55XA5iDyA-Ix_xKJZPbxMiYaCuG

READ ME

Matrix Chain Multiplication is efficiently solved using Dynamic Programming to find the minimum number of scalar multiplications.\
 The algorithm has a **time complexity of O(n³)** and a **space complexity of O(n²)**.\
 The execution time is measured using `time.perf_counter()` and may vary depending on the system.
"""

