# -*- coding: utf-8 -*-
"""READ ME -5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTihPxYr4ygiWbLZH0AhmYNUl60gXqa8

READ ME 5

The 0/1 Knapsack problem is efficiently solved using Dynamic Programming to find the maximum possible value within the given capacity.\
 The algorithm has a **time complexity of O(n × W)** and a **space complexity of O(n × W)**.\
 The execution time is measured using `time.perf_counter()` and may vary depending on the system.
"""

